<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FUT_Button_Close</name>
   <tag></tag>
   <elementGuidId>d5d2d37e-3086-4d89-bf82-328a994c7494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@ng-if='button.click'][contains(.,'Close')]
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@ng-if='button.click'][contains(.,'Close')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@ng-if='button.click'][contains(.,'Close')]</value>
   </webElementProperties>
</WebElementEntity>
